### ISSUE TITLE
Issue in CheckContainedControlsConsistency

### ISSUE THREAD

**Issue by WaynePhillipsEA** [EduardoVB/SSTabEx#2]
Just something I noticed while looking in this area;

```
                            For t2 = 0 To mTabs - 1
                                For c2 = 1 To mTabData(t).Controls.Count
                                    If mTabData(t).Controls(c) = iCtlName Then
                                        iFound = True
                                    End If
                                Next c2
                            Next t2
```

Looks like it should be `mTabData(t2).Controls.Count` and `mTabData(t2).Controls(c2)` ?

**Comment by EduardoVB** [comment]
It has to be, otherwise the code doesn't make sense.

It was a protection because sometimes, I don't remember exactly, but I think in some situations in the VB6 IDE when the control was running in source code and there was an error, the control list was not saved properly, in consistency with the controls actually on the SSTabEx, according to VB6.
