### ISSUE TITLE
Please add a licence

### ISSUE THREAD

**Issue by iainnicol** [EduardoVB/SSTabEx#3]
Thank you for creating this modern alternative to SSTab, and releasing the source on GitHub.

I was hoping you'd release this under an explicit open source licence. Is that something you'd consider? Thanks.

**Comment by EduardoVB** [comment]
I have a first draft:

1. You can do whatever you want with it until I change my mind.
2. If I ever change my mind, you'll still be granted the right to do whatever you want with it (and whatever you need to do, commercially or otherwise), but only if it doesn't hurt my business.
3. It is provided "as is", without express or implied warranty. Use it at your own risk.
4. If you are a large corporation of more than 1000 employees you are granted nothing (in any case contact privately).

**Comment by iainnicol** [comment]
lol, I mean, I tend to prefer a standard licence, whether it's permissive (MIT or Apache etc) or more restrictive/copyleft (LGPL, GPL, AGPL etc). That said, if you don't want to, that's obviously your choice.

Your "doesn't hurt my business" slightly reminds of of Douglas Crockford's "The Software shall be used for Good, not Evil". On one hand it's reasonable and actually quite funny, although on the other it's not compatible with open source licences.

**Comment by EduardoVB** [comment]
I added a fourth condition.

Why do you need a license?

**Comment by iainnicol** [comment]
Need's a strong word. But would I certainly appreciate, yes, because I have an interest both in VB and open source.

One day I'm going to finish my open source VB6 compiler, although the truth is it's vapourware compared to Twinbasic. Anyway, thanks for considering.

**Comment by EduardoVB** [comment]
> Anyway, thanks for considering.

I'm not sure about choosing a standard license now, but if you ever have your compiler more or less finished and this issue becomes important, please contact me again. I intend to help the VBx community with my contributions.

**Comment by iainnicol** [comment]
Very reasonable, thanks.
